/* eslint-disable react/no-unescaped-entities */
import React from 'react';
// @ts-ignore
import Layout from 'components/Layout';
import styled from 'styled-components';

const index = () => {
  const Title = styled.h3`
    font-size: 4rem;
    margin: 0;

    span {
      color: rgb(25, 25, 112);
    }
  `;
  const SubText = styled.h3`
    font-size: 1.8rem;
    color: #ccc;
  `;
  const Paragraph = styled.p`
    margin-top: 1rem;
    font-size: 1.6rem;
  `;

  const PrivacyWrapper = styled.div`
    padding: 5rem 0rem;
  `;
  const ListContainer = styled.div`
    list-style: none;
    li {
      width: 90%;
      padding-left: 2rem;
      font-size: 1.6rem;
      position: relative;
      span {
        border-radius: 0.25rem;
        left: 0;
        top: 1rem;
        background: rgba(25, 25, 112, 0.668);
        height: 0.8rem;
        width: 0.8rem;
        position: absolute;
      }
    }
  `;
  return (
    <Layout>
      <PrivacyWrapper>
        <SubText>AGGREMENT</SubText>
        <Title className="poppins_bold_700">
          Terms & <span>Conditions</span>
        </Title>

        <Paragraph className="poppins_regular_400">
          Please read the Terms and Conditions carefully before using
          Hexgrade.com.
        </Paragraph>
        <Paragraph className="poppins_regular_400">
          This electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </Paragraph>
        <Paragraph className="poppins_regular_400">
          <h2 className="poppins_regular_400">Introductions</h2>
          Welcome to hexgrade.com. Hexgrade is a portfolio management service
          for your professional career and these are the terms and conditions
          governing your access and use of Hexgrade along with its related
          sub-domains, sites, mobile app, services and tools (the "Site"). By
          using the Site, you hereby accept these terms and conditions
          (including the linked information herein) and represent that you agree
          to comply with these terms and conditions (the "User Agreement"). This
          User Agreement is deemed effective upon your use of the Site which
          signifies your acceptance of these terms. If you do not agree to be
          bound by this User Agreement please do not access, register with or
          use this Site.
        </Paragraph>
        <Paragraph className="poppins_regular_400">
          <h2 className="poppins_regular_400">Condition of use</h2>
          <ListContainer className="poppins_regular_400">
            <li>
              <span />
              User shall follow all the necessary rules and regulations of the
            </li>
            <li>
              <span />
              User shall not use the Site for any illegal or unauthorized
            </li>
            <li>
              <span />
              User shall not use the Site for any fraudulent purpose
            </li>
          </ListContainer>
        </Paragraph>
        <Paragraph className="poppins_regular_400">
          <h2 className="poppins_regular_400">Your Account</h2>
          To access certain services offered by the platform, we may require
          that you create an account with us or provide personal information to
          complete the creation of an account. We may at any time in our sole
          and absolute discretion, invalidate the username and/or password
          without giving any reason or prior notice and shall not be liable or
          responsible for any losses suffered by, caused by, arising out of, in
          connection with or by reason of such request or invalidation.
          <br />
          You are responsible for maintaining the confidentiality of your user
          identification, password, account details and related private
          information. You agree to accept this responsibility and ensure your
          account and its related details are maintained securely at all times
          and all necessary steps are taken to prevent misuse of your account.
          You should inform us immediately if you have any reason to believe
          that your password has become known to anyone else, or if the password
          is being, or is likely to be, used in an unauthorized manner. You
          agree and acknowledge that any use of the Site and related services
          offered and/or any access to private information, data or
          communications using your account and password shall be deemed to be
          either performed by you or authorized by you as the case may be. You
          agree to be bound by any access of the Site and/or use of any services
          offered by the Site (whether such access or use are authorized by you
          or not). You agree that we shall be entitled (but not obliged) to act
          upon, rely on or hold you solely responsible and liable in respect
          thereof as if the same were carried out or transmitted by you. You
          further agree and acknowledge that you shall be bound by and agree to
          fully indemnify us against any and all losses arising from the use of
          or access to the Site through your account.
        </Paragraph>
        <Paragraph className="poppins_regular_400">
          Please ensure that the details you provide us with are correct and
          complete at all times. You are obligated to update details about your
          account in real time by accessing your account online. For pieces of
          information you are not able to update by accessing Your Account on
          the Site, you must inform us via our customer service communication
          channels to assist you with these changes. We reserve the right to
          refuse access to the Site, terminate accounts, remove or edit content
          at any time without prior notice to you. We may at any time in our
          sole and absolute discretion, request that you update your Personal
          Data or forthwith invalidate the account or related details without
          giving any reason or prior notice and shall not be liable or
          responsible for any losses suffered by or caused by you or arising out
          of or in connection with or by reason of such request or invalidation.
          You hereby agree to change your password from time to time and to keep
          your account secure and also shall be responsible for the
          confidentiality of your account and liable for any disclosure or use
          (whether such use is authorised or not) of the username and/or
          password.
        </Paragraph>

        <Paragraph className="poppins_regular_400">
          <h2 className="poppins_regular_400">Privacy</h2>
          Please review our Privacy Agreement, which also governs your visit to
          the Site. The personal information / data provided to us by you or
          your use of the Site will be treated as strictly confidential, in
          accordance with the Privacy Agreement and applicable laws and
          regulations. If you object to your information being transferred or
          used in the manner specified in the Privacy Agreement, please do not
          use the Site.
        </Paragraph>
        <Paragraph className="poppins_regular_400">
          <h2 className="poppins_regular_400">
            CONTINUED AVAILABILITY OF THE SITE
          </h2>
          We will do our utmost to ensure that access to the Site is
          consistently available and is uninterrupted and error-free. However,
          due to the nature of the Internet and the nature of the Site, this
          cannot be guaranteed. Additionally, your access to the Site may also
          be occasionally suspended or restricted to allow for repairs,
          maintenance, or the introduction of new facilities or services at any
          time without prior notice. We will attempt to limit the frequency and
          duration of any such suspension or restriction. We will attempt to
          limit the frequency and duration of any such suspension or
          restriction.
        </Paragraph>

        <Paragraph className="poppins_regular_400">
          <h2 className="poppins_regular_400">GOVERNING LAW AND JURIDICTION</h2>
          These terms and conditions are governed by and construed in accordance
          with the laws of the Federal Democratic Republic of Nepal. You agree,
          as we do, to submit to the exclusive jurisdiction of the courts in
          Kathmandu.
        </Paragraph>
      </PrivacyWrapper>
    </Layout>
  );
};

export default index;
